### ISSUE TITLE
why the Savzky-Golay? 

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/isotherm-fitting#12]
what is this supposed to do 

https://github.com/gSulpizio/isotherm-analysis/blob/1013b45d10287ad30288894708536716ff55f85d/src/script.ts#L4-L7

**Comment by gSulpizio** [comment]
Honestly no idea, I'll delete this. Is there a reason why i can't just import SG but have to go through require?

**Comment by kjappelbaum** [comment]
you should be able to, and you already did somewhere else https://github.com/gSulpizio/parser/blob/67a979ae83f7dfabb6ba261db9cafbfe1069cf65/src/getSANPlot.js#L3
