### ISSUE TITLE
`BetLinearFitDouble` simply duplicates `BETFitLinear` ? 

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/isotherm-fitting#13]
https://github.com/gSulpizio/isotherm-analysis/blob/1013b45d10287ad30288894708536716ff55f85d/src/BETFitLinearDouble.ts#L14

**Comment by gSulpizio** [comment]
Basically what I said in the other issue [here](https://github.com/gSulpizio/isotherm-fitting/issues/11#issuecomment-845430165), it was just an idea.

**Comment by kjappelbaum** [comment]
the issue was more concerting the function name

**Comment by gSulpizio** [comment]
Done! It was a mistake
