### ISSUE TITLE
can you define constants in only one file 

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/isotherm-fitting#27]
e.g., instead of defining 

https://github.com/gSulpizio/isotherm-fitting/blob/79b1278285b3c82b6fd746aa20a8bfba14462e8b/src/isostericHeat/isostericHeatFromData.ts#L24
 
in every file it might be better to only have one source of truth, i.e., one file and import constants from there

**Comment by gSulpizio** [comment]
Done!
