### ISSUE TITLE
why is this here? 

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/isotherm-fitting#31]
https://github.com/gSulpizio/isotherm-fitting/blob/79b1278285b3c82b6fd746aa20a8bfba14462e8b/src/isostericHeat/getlnP.ts#L30

**Comment by gSulpizio** [comment]
So this is to make an array of  `ln(P)` of every dataSet for one specific loading (so every temperature) and then use that array to make a linear regression on the array. As we don't need that anymore, we replace it by the `ln(P)`of the next loading. Does that make sense?

**Comment by kjappelbaum** [comment]
i still think that the unused `lnP` array and this empty push is weird

**Comment by gSulpizio** [comment]
It's gone
