### ISSUE TITLE
`fittedParameters` in docstring confusing 

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/isotherm-fitting#32]
https://github.com/gSulpizio/isotherm-fitting/blob/79b1278285b3c82b6fd746aa20a8bfba14462e8b/src/isostericHeat/getlnP.ts#L41

**Comment by kjappelbaum** [comment]
especially, is the output from the optimization an array or an object?

**Comment by gSulpizio** [comment]
The output is an array, I updated the docstring, I hope it is clearer now
