### ISSUE TITLE
test for isosteric heat of adsorption

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/isotherm-fitting#37]
can you add a test for 

```
    for (let j = 0; j < data.length; j++) {
      lnP.push(data[j].lnP[i] + Math.log(saturationPressure[j]));
    }
    regression = new SimpleLinearRegression(inverseTemperatures, lnP);
```

using the data from the Excel sheet?

**Comment by gSulpizio** [comment]
destructured, made a test for it: [test](https://github.com/gSulpizio/isotherm-fitting/blob/209a10545db19de1795031a08746aa895eafc9e3/src/isostericHeat/__tests__/getSlopes.test.ts#L1), [function](https://github.com/gSulpizio/isotherm-fitting/blob/209a10545db19de1795031a08746aa895eafc9e3/src/isostericHeat/getSlopes.ts#L1)
