### ISSUE TITLE
if you want to keep this as your own package

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/isotherm-fitting#7]
- [x] please rename to avoid name clashes
- [ ] add the github actions (then i can also easily directly on GitHub what passes fails and do not have to open vs code, pull, run npm) 
- [ ] follow naming conventions
- [ ] export reasonable things and remove https://github.com/gSulpizio/isotherm-analysis/blob/1013b45d10287ad30288894708536716ff55f85d/src/index.ts#L1-L7

in any case, it would be good if you can settle some things down that work

**Comment by gSulpizio** [comment]
for the actions I'm not sure what to do, could you be a bit more specific please?

**Comment by kjappelbaum** [comment]
for the github actions i'd add at least the nodejs workflow (https://github.com/cheminfo/cheminfo-types/tree/main/.github/workflows) that runs eslint and jest

**Comment by gSulpizio** [comment]
Honestly I'm not sure here, should I copy the folder or take the nodejs for azure workflow that's available?
