### ISSUE TITLE
organization and unit tests

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/isotherm-fitting#8]
the way you can help others and yourself is to really write tests for atomic parts and keep atomic parts separate. For example, for the model functions I would make a folder and put every model function in its own file 

```
modelFunctions 
   __tests___
      Langmuir.test.ts
   Langmuir.ts
```

and then you simply check if the model functions return valid outputs. 

I would use the same approach for the fitting parts.

**Comment by gSulpizio** [comment]
done!
