### ISSUE TITLE
initial guess

### ISSUE THREAD

**Issue by kjappelbaum** [gSulpizio/isotherm-fitting#9]
why your question here https://github.com/gSulpizio/isotherm-analysis/blob/1013b45d10287ad30288894708536716ff55f85d/src/langmuirDoubleFit.ts#L29-L30
does this have such a drastic influence? don't you converge to the same minimum if you change the initial conditions a bit?

**Comment by gSulpizio** [comment]
So it's just to not have exactly the same? The question was more as to why we don't use 0.5 for both?

**Comment by kjappelbaum** [comment]
should still converge to something reasonable, doesn't it?

**Comment by gSulpizio** [comment]
Yes it does, I just didn't understand the choice of 0.4  and 0.6.
